#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$qa_cmd = new Commando\Command();
$color = new Colors\Color();

$qa_cmd->option()
    ->require(true)
    ->describedAs('Ablsolute or relative path to a directory containing Islandora import packages. ' .
        'Trailing slash is optional.')
    ->must(function ($dir_path) {
        if (file_exists($dir_path)) {
            return true;
        } else {
            return false;
        }
    });

$qa_cmd->option('m')
    ->aka('content_model')
    ->require(true)
    ->describedAs('An alias for groups of Islandora content models. Allowed values are ' .
        'single, single_rest_ingester, newspapers, books, compound.')
    ->must(function ($cmodel) {
        $cmodels = array('single', 'single_rest_ingester', 'newspapers', 'books', 'compound');
        return in_array($cmodel, $cmodels);
    });

$qa_cmd->option('s')
    ->aka('strict')
    ->describedAs('If present, iipqa will exit with a code of 1 if it encounters any errors.')
    ->boolean();

$qa_cmd->option('v')
    ->aka('validate_mods')
    ->describedAs('If present, iipqa will validate all MODS XML files in all input packages.')
    ->boolean()
    ->default(false);

$qa_cmd->option('k')
    ->aka('skip_structure')
    ->describedAs('If present, iipqa will skip validating the presence of structure.xml files in compound packages.')
    ->boolean()
    ->default(false);

$qa_cmd->option('l')
    ->aka('log')
    ->describedAs('Path to the log. Default is ./iipqa.log')
    ->default('./iipqa.log');

$qa_cmd->option('p')
    ->aka('post_iipqa')
    ->describedAs('Path to script(s) to run after iipqa performs its tests.');

$content_model = $qa_cmd['content_model'];
$input_path = $qa_cmd[0];

if (strtolower(pathinfo($input_path, PATHINFO_EXTENSION) == 'zip')) {
    $unzipper = new \iipqa\utils\Zip($input_path, $qa_cmd['log'], $qa_cmd);
    if (!$input_path = $unzipper->unzip()) {
        print $color("Structure of zip file extracted to " . $input_path . " is not valid")->yellow() . PHP_EOL;
        exit(1);
    }
}

switch ($content_model) {
    case 'single':
        $qa_framework = new \iipqa\contentmodels\Single($input_path, $qa_cmd['log'], $qa_cmd);
        break;
    case 'single_rest_ingester':
        $qa_framework = new \iipqa\contentmodels\SingleRestIngester($input_path, $qa_cmd['log'], $qa_cmd);
        break;
    case 'newspapers':
        $qa_framework = new \iipqa\contentmodels\Newspapers($input_path, $qa_cmd['log'], $qa_cmd);
        break;
    case 'books':
        $qa_framework = new \iipqa\contentmodels\Books($input_path, $qa_cmd['log'], $qa_cmd);
        break;
    case 'compound':
        $qa_framework = new \iipqa\contentmodels\Compound($input_path, $qa_cmd['log'], $qa_cmd);
        break;
    default:
        exit("Sorry, the content model " . $qa_cmd['content_model'] . " is not recognized ." . PHP_EOL);
}

// We want the content-model-specific tests to run first.
$qa_failures_present = $qa_framework->applyQaTests();

// Then the general tests.
if ($qa_cmd['v']) {
    $mods_validator = new \iipqa\utils\ModsValidator($input_path, $qa_cmd['log'], $qa_cmd);
    if (!$mods_validator->validateMods()) {
        print $color("Some MODS XML files failed validation. Details are available in ")->yellow() .
            $qa_cmd['log'] . PHP_EOL;
        if ($qa_cmd['strict']) {
            exit(1);
        }
    }
}

if (in_array(false, $qa_failures_present)) {
    print $color("Some tests failed. Details are available in ")->yellow() . $qa_cmd['log'] . PHP_EOL;
    if ($qa_cmd['strict']) {
        exit(1);
    }
} else {
    print $color("All tests successful." . PHP_EOL)->green();
}

if (isset($qa_cmd['p']) && strlen($qa_cmd['p'])) {
    if (preg_match("/^\[.+\]$/", $qa_cmd['p'])) {
        $scripts = trim($qa_cmd['p'], "[]");
        $scripts = explode(',', $scripts);
        foreach ($scripts as &$script) {
            $script = trim($script);
            $script = trim($script, '"');
            print "Running post-iipqa script " . $script . PHP_EOL;
            exec($script, $output, $ret);
            if ($ret) {
                print "Post-iipqa script (" . $script . ") failed." . PHP_EOL;
                if ($qa_cmd['strict']) {
                    exit(1);
                }
            }
        }
    } else {
        print "Running post-iipqa script " . $qa_cmd['p'] . PHP_EOL;
        exec($qa_cmd['p'], $output, $ret);
        if ($ret) {
            print "Post-iipqa script (" . $qa_cmd['p'] . ") failed." . PHP_EOL;
            if ($qa_cmd['strict']) {
                exit(1);
            }
        }
    }
}
